# Docker



# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: test
  displayName: Test
  jobs:
  - job: Install
    steps:
    - task: UseNode@1
      inputs:
        version: '12.x'
        checkLatest: true
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
  - job: testNode
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.SourcesDirectory)/Platform/ClientApp'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'test-ci'
          workingDir: '$(Build.SourcesDirectory)/Platform/ClientApp'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish nodejs code coverage reesults'
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Build.SourcesDirectory)/Platform/ClientApp/coverage/cobertura-coverage.xml'
          reportDirectory: '$(Build.SourcesDirectory)/Platform/ClientApp/coverage'
          failIfCoverageEmpty: true
  - job: testDotnetCore 
    displayName: test Dotnet Core
    steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/PlatformUnitTests.csproj'
              testRunTitle: 'Platform Unit tests'

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:


    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Platform/Dockerfile'
        tags: |
          $(tag)